# Site settings
title: swyx/dev/blog
description: 'because swyx.com was taken'
url: 'http://sw-yx.github.io' 
# baseurl: '/'
baseurl: 'http://sw-yx.github.io/'
google_analytics: 'UA-79238211-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Shawn Wang'
  email: swyx@swyx.io
  twitter_username: swyx
  # facebook_username: joshgerdes
  github_username:  sw-yx
  linkedin_username:  shawnswyxwang

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']
